BEGIN
  FOR tbl IN (
    SELECT table_name FROM user_tables WHERE table_name IN (
      'ADDRESS', 'USERS', 'ANIMALS', 'ADOPTIONS', 'ANIMAL_METRICS', 'ADOPTION_STATUS_HISTORY',
      'FAVORITES', 'CARE_SCHEDULE', 'CARE_RESOURCES', 'MEDICAL_HISTORY', 'MEDIA', 'TAGS',
      'ANIMAL_TAGS', 'USER_PREFERENCE_TAGS', 'SYSTEM_NOTIFICATIONS', 'CONVERSATIONS',
      'MESSAGES', 'USER_PREFERENCES', 'SYSTEM_LOGS', 'TESTIMONIALS', 'OWNER_REVIEWS'
    )
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE ' || tbl.table_name || ' CASCADE CONSTRAINTS';
    EXCEPTION WHEN OTHERS THEN
      NULL;
    END;
  END LOOP;
END;
/

SELECT table_name FROM user_tables WHERE table_name IN (
  'ADDRESS', 'USERS', 'ANIMALS', 'ADOPTIONS', 'ANIMAL_METRICS', 'ADOPTION_STATUS_HISTORY', 'FAVORITES', 'CARE_SCHEDULE', 'CARE_RESOURCES', 'MEDICAL_HISTORY', 'MEDIA', 'TAGS', 'ANIMAL_TAGS', 'USER_PREFERENCE_TAGS', 'SYSTEM_NOTIFICATIONS', 'CONVERSATIONS', 'MESSAGES', 'USER_PREFERENCES', 'SYSTEM_LOGS', 'TESTIMONIALS', 'OWNER_REVIEWS'
);

CREATE TABLE address (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  street VARCHAR2(255),
  city VARCHAR2(100) NOT NULL,
  country VARCHAR2(100) NOT NULL,
  postal_code VARCHAR2(20),
  latitude NUMBER(10,8),
  longitude NUMBER(11,8),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username VARCHAR2(50) UNIQUE NOT NULL,
  password_hash VARCHAR2(100) NOT NULL,
  email VARCHAR2(100) UNIQUE NOT NULL,
  first_name VARCHAR2(50),
  last_name VARCHAR2(50),
  phone VARCHAR2(20),
  is_verified NUMBER(1) DEFAULT 0,
  email_token VARCHAR2(255),
  token_expires TIMESTAMP,
  address_id NUMBER,
  role VARCHAR2(20) DEFAULT 'user',
  profile_picture VARCHAR2(255) DEFAULT '/images/profile/default-user-profile.jpg',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_users_address FOREIGN KEY (address_id) REFERENCES address(id),
  CONSTRAINT chk_users_role CHECK (role IN ('user', 'admin', 'shelter'))
);

CREATE TABLE animals (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) NOT NULL,
  species VARCHAR2(50) NOT NULL,
  breed VARCHAR2(100),
  age NUMBER(3,1),
  gender VARCHAR2(10),
  size_category VARCHAR2(20),
  weight_kg NUMBER(5,2),
  color VARCHAR2(100),
  health_status VARCHAR2(255),
  description CLOB,
  adoption_status VARCHAR2(20) DEFAULT 'available',
  adoption_fee NUMBER(8,2),
  address_id NUMBER,
  shelter_id NUMBER,
  relation_with_others VARCHAR2(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_animals_address FOREIGN KEY (address_id) REFERENCES address(id),
  CONSTRAINT fk_animals_shelter FOREIGN KEY (shelter_id) REFERENCES users(id),
  CONSTRAINT chk_animals_gender CHECK (gender IN ('male', 'female', 'unknown')),
  CONSTRAINT chk_animals_size CHECK (size_category IN ('small', 'medium', 'large')),
  CONSTRAINT chk_animals_status CHECK (adoption_status IN ('available', 'pending', 'adopted'))
);

CREATE TABLE adoptions (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  animal_id NUMBER NOT NULL,
  request_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  adoption_date TIMESTAMP,
  status VARCHAR2(50) DEFAULT 'open',
  CONSTRAINT fk_adoptions_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_adoptions_animal FOREIGN KEY (animal_id) REFERENCES animals(id),
  CONSTRAINT chk_adoption_status CHECK (status IN ('open', 'pending', 'approved', 'rejected', 'completed'))
);

CREATE TABLE animal_metrics (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    animal_id NUMBER NOT NULL,
    favorites_count NUMBER DEFAULT 0,
    views_count NUMBER DEFAULT 0,
    adoption_requests_count NUMBER DEFAULT 0,
    avg_time_to_adoption NUMBER, -- days
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_animal_metrics_animal FOREIGN KEY (animal_id) REFERENCES animals(id),
    CONSTRAINT uk_animal_metrics UNIQUE (animal_id)
);

CREATE TABLE adoption_status_history (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    adoption_id NUMBER NOT NULL,
    old_status VARCHAR2(50),
    new_status VARCHAR2(50),
    changed_by NUMBER,
    change_reason VARCHAR2(500),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adoption_hist_adoption FOREIGN KEY (adoption_id) REFERENCES adoptions(id),
    CONSTRAINT fk_adoption_hist_user FOREIGN KEY (changed_by) REFERENCES users(id)
);

CREATE TABLE favorites (
  user_id NUMBER NOT NULL,
  animal_id NUMBER NOT NULL,
  favorited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_favorites PRIMARY KEY (user_id, animal_id),
  CONSTRAINT fk_favorites_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_favorites_animal FOREIGN KEY (animal_id) REFERENCES animals(id)
);

CREATE TABLE care_schedule (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  animal_id NUMBER NOT NULL,
  activity VARCHAR2(100),
  hour VARCHAR2(10),
  frequency VARCHAR2(50),
  CONSTRAINT fk_care_schedule_animal FOREIGN KEY (animal_id) REFERENCES animals(id)
);

CREATE TABLE care_resources (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  animal_id NUMBER NOT NULL,
  resource_type VARCHAR2(50),
  title VARCHAR2(255),
  content CLOB,
  CONSTRAINT fk_care_resources_animal FOREIGN KEY (animal_id) REFERENCES animals(id)
);

CREATE TABLE medical_history (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  animal_id NUMBER NOT NULL,
  description CLOB,
  record_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_medical_history_animal FOREIGN KEY (animal_id) REFERENCES animals(id)
);

CREATE TABLE media (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  animal_id NUMBER NOT NULL,
  type VARCHAR2(20),
  file_path VARCHAR2(255),
  CONSTRAINT fk_media_animal FOREIGN KEY (animal_id) REFERENCES animals(id)
);

CREATE TABLE tags (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE animal_tags (
  animal_id NUMBER NOT NULL,
  tag_id NUMBER NOT NULL,
  CONSTRAINT pk_animal_tags PRIMARY KEY (animal_id, tag_id),
  CONSTRAINT fk_animal_tags_animal FOREIGN KEY (animal_id) REFERENCES animals(id),
  CONSTRAINT fk_animal_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE user_preference_tags (
  user_id NUMBER NOT NULL,
  tag_id NUMBER NOT NULL,
  CONSTRAINT pk_user_preference_tags PRIMARY KEY (user_id, tag_id),
  CONSTRAINT fk_user_tags_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_user_tags_tag FOREIGN KEY (tag_id) REFERENCES tags(id)
);


CREATE TABLE system_notifications (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    notification_type VARCHAR2(50),
    title VARCHAR2(200),
    message CLOB,
    is_read NUMBER(1) DEFAULT 0,
    priority_level VARCHAR2(20) DEFAULT 'normal',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_notification_priority CHECK (priority_level IN ('low', 'normal', 'high', 'urgent'))
);

CREATE TABLE conversations (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    participant1_id NUMBER NOT NULL,
    participant2_id NUMBER NOT NULL,
    animal_id NUMBER,
    conversation_type VARCHAR2(50) DEFAULT 'adoption_inquiry',
    status VARCHAR2(20) DEFAULT 'active',
    last_message_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_conv_participant1 FOREIGN KEY (participant1_id) REFERENCES users(id),
    CONSTRAINT fk_conv_participant2 FOREIGN KEY (participant2_id) REFERENCES users(id),
    CONSTRAINT fk_conv_animal FOREIGN KEY (animal_id) REFERENCES animals(id),
    CONSTRAINT chk_conv_type CHECK (conversation_type IN ('adoption_inquiry', 'general', 'support', 'follow_up')),
    CONSTRAINT chk_conv_status CHECK (status IN ('active', 'archived', 'blocked'))
);

CREATE TABLE messages (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    conversation_id NUMBER NOT NULL,
    sender_id NUMBER NOT NULL,
    message_text CLOB NOT NULL,
    message_type VARCHAR2(20) DEFAULT 'text',
    is_read NUMBER(1) DEFAULT 0,
    read_at TIMESTAMP,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT chk_message_type CHECK (message_type IN ('text', 'image', 'document', 'system'))
);

CREATE TABLE user_preferences (
    user_id NUMBER PRIMARY KEY,
    preferred_species CLOB,
    preferred_age_range VARCHAR2(50),
    max_distance NUMBER DEFAULT 50,
    home_type VARCHAR2(50),
    has_yard NUMBER(1) DEFAULT 0,
    has_other_pets NUMBER(1) DEFAULT 0,
    experience_level VARCHAR2(20),
    available_time VARCHAR2(50),
    activity_level VARCHAR2(20),
    noise_tolerance VARCHAR2(20),
    budget_range VARCHAR2(50),
    special_needs_ok NUMBER(1) DEFAULT 0,
    preferences_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    matching_enabled NUMBER(1) DEFAULT 1,
    CONSTRAINT fk_user_prefs_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_prefs_age CHECK (preferred_age_range IN ('any', 'puppy', 'young', 'adult', 'senior')),
    CONSTRAINT chk_prefs_home CHECK (home_type IN ('apartment', 'house', 'farm', 'other')),
    CONSTRAINT chk_prefs_experience CHECK (experience_level IN ('beginner', 'intermediate', 'expert')),
    CONSTRAINT chk_prefs_time CHECK (available_time IN ('minimal', 'moderate', 'extensive')),
    CONSTRAINT chk_prefs_activity CHECK (activity_level IN ('low', 'medium', 'high')),
    CONSTRAINT chk_prefs_noise CHECK (noise_tolerance IN ('low', 'medium', 'high')),
    CONSTRAINT chk_prefs_budget CHECK (budget_range IN ('low', 'medium', 'high'))
);

CREATE TABLE system_logs (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    log_type VARCHAR2(50) NOT NULL,
    user_id NUMBER,
    animal_id NUMBER,
    action VARCHAR2(100) NOT NULL,
    details CLOB,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    session_id VARCHAR2(100),
    execution_time NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_logs_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_logs_animal FOREIGN KEY (animal_id) REFERENCES animals(id),
    CONSTRAINT chk_log_type CHECK (log_type IN ('user_action', 'system_event', 'error', 'security', 'performance'))
);

CREATE TABLE testimonials (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    testimonial_text CLOB NOT NULL,
    rating NUMBER(2,1) DEFAULT 5,
    location VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_testimonials_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT chk_testimonial_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE owner_reviews (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    reviewer_id NUMBER NOT NULL,
    reviewed_owner_id NUMBER NOT NULL,
    adoption_id NUMBER NOT NULL,
    rating NUMBER(2,1) NOT NULL,
    review_text CLOB,
    communication_rating NUMBER(1) CHECK (communication_rating BETWEEN 1 AND 5),
    pet_condition_rating NUMBER(1) CHECK (pet_condition_rating BETWEEN 1 AND 5),
    process_rating NUMBER(1) CHECK (process_rating BETWEEN 1 AND 5),
    would_recommend NUMBER(1) DEFAULT 1 CHECK (would_recommend IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_owner_reviews_reviewer FOREIGN KEY (reviewer_id) REFERENCES users(id),
    CONSTRAINT fk_owner_reviews_owner FOREIGN KEY (reviewed_owner_id) REFERENCES users(id),
    CONSTRAINT fk_owner_reviews_adoption FOREIGN KEY (adoption_id) REFERENCES adoptions(id),
    CONSTRAINT chk_owner_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT uk_owner_reviews_adoption UNIQUE (adoption_id)
);

CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_animals_species ON animals(species);
CREATE INDEX idx_animals_status ON animals(adoption_status);
CREATE INDEX idx_animals_shelter ON animals(shelter_id);
CREATE INDEX idx_animals_location ON animals(address_id);
CREATE INDEX idx_adoptions_user ON adoptions(user_id);
CREATE INDEX idx_adoptions_animal ON adoptions(animal_id);
CREATE INDEX idx_adoptions_status ON adoptions(status);
CREATE INDEX idx_notifications_user_unread ON system_notifications(user_id, is_read, created_at);
CREATE INDEX idx_notifications_expires ON system_notifications(expires_at);
CREATE INDEX idx_messages_conversation_sent ON messages(conversation_id, sent_at);
CREATE INDEX idx_messages_unread ON messages(is_read, sent_at);
CREATE INDEX idx_system_logs_type_date ON system_logs(log_type, created_at);
CREATE INDEX idx_system_logs_user ON system_logs(user_id, created_at);
CREATE INDEX idx_animal_metrics_favorites ON animal_metrics(favorites_count DESC);
CREATE INDEX idx_animal_metrics_views ON animal_metrics(views_count DESC);
CREATE INDEX idx_favorites_user ON favorites(user_id, favorited_at);
CREATE INDEX idx_favorites_animal ON favorites(animal_id, favorited_at);
CREATE INDEX idx_conversations_participant1 ON conversations(participant1_id, last_message_at);
CREATE INDEX idx_conversations_participant2 ON conversations(participant2_id, last_message_at);
CREATE INDEX idx_conversations_animal ON conversations(animal_id);
CREATE INDEX idx_animal_tags_animal ON animal_tags(animal_id);
CREATE INDEX idx_animal_tags_tag ON animal_tags(tag_id);
CREATE INDEX idx_user_tags_user ON user_preference_tags(user_id);
CREATE INDEX idx_address_city ON address(city);
CREATE INDEX idx_address_coords ON address(latitude, longitude);
CREATE INDEX idx_testimonials_user ON testimonials(user_id, created_at);
CREATE INDEX idx_owner_reviews_reviewer ON owner_reviews(reviewer_id, created_at);
CREATE INDEX idx_owner_reviews_owner ON owner_reviews(reviewed_owner_id, created_at);
CREATE INDEX idx_owner_reviews_rating ON owner_reviews(rating DESC);
COMMIT;